add bluepill versions, make script more robust

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1,50 +1,58 @@
-format_version: 4
+format_version: 6
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 
 app:
   envs:
-  # If you want to share this step into a StepLib
-  - BITRISE_STEP_ID: bluepill-build-test-for-ios
-  - BITRISE_STEP_VERSION: "0.1.1"
   - BITRISE_STEP_GIT_CLONE_URL: https://github.com/HealthEngineAU/bitrise-step-bluepill-build-test-for-ios.git
-  - MY_STEPLIB_REPO_FORK_GIT_URL: $MY_STEPLIB_REPO_FORK_GIT_URL
+  - BITRISE_SAMPLE_APP: https://github.com/reececomo/sample-apps-ios-workspace-swift.git
 
 workflows:
   test:
+    before_run:
+    - audit-this-step
     steps:
+    - script:
+        title: Remove existing _tmp dir (if exists)
+        inputs:
+        - content: rm -rf _tmp
     - change-workdir:
         title: Switch working dir to test / _tmp dir
-        description: |-
-          To prevent step testing issues, like referencing relative
-          files with just './some-file' in the step's code, which would
-          work for testing the step from this directory directly
-          but would break if the step is included in another `bitrise.yml`.
         run_if: true
         inputs:
         - path: ./_tmp
         - is_create_path: true
+    - script:
+        title: Clone Sample App
+        inputs:
+        - content: git clone $BITRISE_SAMPLE_APP .
     - path::./:
-        title: Step Test
-        description: |-
-          The example input has a default value,
-          you can overwrite it if you want to, just like we did below,
-          but the step would use the default value specified in the `step.yml`
-          file if you would not specify another value.
+        title: Test bluepill-build-run-for-ios
         run_if: true
         inputs:
-        - app_name: HealthEngine
-        - workspace: HealthEngine.xcworkspace
-        - scheme: HealthEngine
+        - bluepill_version: bluepill_4_1_1__xcode_10_2
+        - target_name: sample-apps-ios-workspace-swift
+        - workspace: sample-apps-ios-workspace-swift.xcworkspace
+        - scheme: sample-apps-ios-workspace-swift
         - derived_data_path: build
         - device_type: "iPhone SE"
         - bluepill_output_dir: bluepill-output
-        - failure_tolerance: 1
+        - test_result_env_var: MY_TESTS
     - script:
+        title: Check the test results are set
         inputs:
         - content: |
             #!/bin/bash
-            echo "This output was generated by the Step (EXAMPLE_STEP_OUTPUT): $EXAMPLE_STEP_OUTPUT"
+            set -e
 
+            if [ -z "$MY_TESTS" ]; then
+              echo "Test result string env var failed to set!"
+              exit -1
+            fi
+
+            if [ -z "$MY_TESTS_MARKDOWN" ]; then
+              echo "Markdown-formatted test result string env var failed to set!"
+              exit -1
+            fi
 
   # ----------------------------------------------------------------
   # --- workflows to Share this step into a Step Library
@@ -56,43 +64,3 @@ workflows:
             #!/bin/bash
             set -ex
             stepman audit --step-yml ./step.yml
-
-  share-this-step:
-    envs:
-      # if you want to share this step into a StepLib
-      - MY_STEPLIB_REPO_FORK_GIT_URL: $MY_STEPLIB_REPO_FORK_GIT_URL
-      - BITRISE_STEP_ID: $BITRISE_STEP_ID
-      - BITRISE_STEP_VERSION: $BITRISE_STEP_VERSION
-      - BITRISE_STEP_GIT_CLONE_URL: $BITRISE_STEP_GIT_CLONE_URL
-    description: |-
-      If this is the first time you try to share a Step you should
-      first call: $ bitrise share
-
-      This will print you a guide, and information about how Step sharing
-      works. Please read it at least once!
-
-      As noted in the Step sharing guide you'll have to fork the
-      StepLib you want to share this step into. Once you're done with forking
-      the repository you should set your own fork's git clone URL
-      in the `.bitrise.secrets.yml` file, or here in the `envs` section,
-      as the value of the `MY_STEPLIB_REPO_FORK_GIT_URL` environment.
-
-      You're now ready to share this Step, just make sure that
-      the `BITRISE_STEP_ID` and `BITRISE_STEP_VERSION`
-      environments are set to the desired values!
-
-      To share this Step into a StepLib you can just run: $ bitrise run share-this-step
-
-      Once it finishes the only thing left is to actually create a Pull Request,
-      the way described in the guide printed at the end of the process.
-    before_run:
-    - audit-this-step
-    steps:
-    - script:
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -ex
-            bitrise share start -c "${MY_STEPLIB_REPO_FORK_GIT_URL}"
-            bitrise share create --stepid "${BITRISE_STEP_ID}" --tag "${BITRISE_STEP_VERSION}" --git "${BITRISE_STEP_GIT_CLONE_URL}"
-            bitrise share finish
